kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo 
    spec:
      containers:
      - name: todo
        image: docker.io/solitanhuttu/todo:latest
        ports:
          - containerPort: 8000
        env: 
          - name: PORT
            value: "8000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
       
